"""Export and shareable snapshot.

Wraps a completed analysis result with metadata to produce a
self-contained, shareable snapshot file. Supports JSON and Markdown
output formats.
"""

from __future__ import annotations

from datetime import datetime, timezone

from pydantic import BaseModel, Field

from projectbridge import __version__
from projectbridge.schema import AnalysisResult, ProjectSpec, Skill


class Snapshot(BaseModel):
    """A shareable skill-gap snapshot.

    Self-contained file that includes the analysis result plus metadata
    so it is interpretable without the engine running.
    """

    exported_at: str = Field(
        description="ISO 8601 timestamp of when the snapshot was created.",
    )
    engine_version: str = Field(
        description="ProjectBridge engine version that produced the analysis.",
    )
    schema_version: str = Field(
        description="Output schema version.",
    )
    analysis: AnalysisResult = Field(
        description="The complete analysis result.",
    )


def create_snapshot(result: AnalysisResult) -> Snapshot:
    """Wrap an analysis result in a shareable snapshot.

    Args:
        result: A completed analysis result.

    Returns:
        A :class:`Snapshot` with metadata and the analysis result.
    """
    return Snapshot(
        exported_at=datetime.now(timezone.utc).isoformat(),
        engine_version=__version__,
        schema_version=result.schema_version,
        analysis=result,
    )


def _skill_list(skills: list[Skill]) -> str:
    """Render a list of skills as a Markdown bullet list."""
    if not skills:
        return "_None detected._\n"
    return "".join(f"- {s.name} ({s.category.value})\n" for s in skills)


def render_markdown(result: AnalysisResult) -> str:
    """Render an analysis result as a Markdown document.

    Args:
        result: A completed analysis result.

    Returns:
        A Markdown-formatted string.
    """
    lines: list[str] = []
    lines.append("# ProjectBridge Analysis\n\n")

    # Strengths
    lines.append("## Strengths\n\n")
    lines.append(_skill_list(result.strengths))
    lines.append("\n")

    # Gaps
    lines.append("## Skill Gaps\n\n")
    lines.append(_skill_list(result.gaps))
    lines.append("\n")

    # Portfolio Insights
    if result.portfolio_insights:
        lines.append("## Portfolio Insights\n\n")
        for insight in result.portfolio_insights:
            lines.append(f"- {insight.message}\n")
        lines.append("\n")

    # Recommendations
    lines.append("## Recommendations\n\n")
    if not result.recommendations:
        lines.append("_No recommendations generated._\n")
    else:
        for rec in result.recommendations:
            lines.append(f"### {rec.title}\n\n")
            lines.append(f"{rec.description}\n\n")
            if rec.skill_context:
                lines.append(f"> {rec.skill_context}\n\n")
            skills = ", ".join(rec.skills_addressed)
            lines.append(f"- **Skills addressed:** {skills}\n")
            lines.append(f"- **Estimated scope:** {rec.estimated_scope.value}\n")
            lines.append("\n")

    # Interview Preparation
    if result.interview_topics:
        lines.append("## Interview Preparation\n\n")
        for entry in result.interview_topics:
            lines.append(f"### {entry.skill}\n\n")
            for topic in entry.topics:
                lines.append(f"- {topic}\n")
            lines.append("\n")

    # Footer
    lines.append("---\n\n")
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines.append(f"_Generated by ProjectBridge v{__version__} on {ts}_\n")

    return "".join(lines)


def render_project_spec(spec: ProjectSpec) -> str:
    """Render a project spec as a Markdown document.

    Args:
        spec: A generated project specification.

    Returns:
        A Markdown-formatted string.
    """
    lines: list[str] = []

    # Header
    lines.append(f"# Project Spec: {spec.title}\n\n")
    lines.append(f"**Difficulty:** {spec.difficulty.value.capitalize()}\n")
    lines.append(f"**Skills:** {', '.join(spec.skills_addressed)}\n\n")

    # Description
    lines.append("## Project Description\n\n")
    lines.append(f"{spec.description}\n\n")

    # Key Features
    lines.append("## Key Features\n\n")
    lines.append("Build these features to demonstrate your understanding:\n\n")
    for i, feature in enumerate(spec.features, 1):
        lines.append(f"{i}. {feature}\n")
    lines.append("\n")

    # Why These Skills Matter
    if spec.why_skills_matter:
        lines.append("## Why These Skills Matter\n\n")
        lines.append(f"{spec.why_skills_matter}\n\n")

    # Documentation & Resources
    if spec.doc_links:
        lines.append("## Documentation & Resources\n\n")
        for link in spec.doc_links:
            lines.append(f"- **{link.skill}** — [{link.label}]({link.url})\n")
        lines.append("\n")

    # Footer
    lines.append("---\n\n")
    lines.append(f"_Generated by ProjectBridge v{__version__}_\n")

    return "".join(lines)
